name: Deployment pipeline

on:
  schedule:
        - cron:  '*/15 * * * *'
jobs:
  periodic_healtcheck:
    runs-on: ubuntu-18.04
    steps:
    - name: check health of url
      uses: jtalk/url-health-check-action@v1.4
      with:
        url: "https://safe-escarpment-40383.herokuapp.com/health"